/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clase.OperatiiOutFisier;
import clase.TrenMarfa;
import clase.TrenPasageri;
import claseAbstracte.Tren;
import java.awt.Component;
import java.awt.image.ImageObserver;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Airinei
 */
public class formular extends javax.swing.JFrame {
    DefaultTableModel model;
    ArrayList<Tren> listaTren;
    ArrayList<Tren> listaTrimis;
    Socket soc;
    OutputStream out;
    InputStream in;
    ObjectInputStream fin;
    ObjectOutputStream fout;
    /**
     * Creates new form formular
     */
    public formular() {
        initComponents();
        model=(DefaultTableModel) jTable1.getModel();
        listaTren = new ArrayList<Tren>();
        listaTrimis= new ArrayList<Tren>();
        textFisier.setText("p.txt");
        tpR.doClick();
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textFisier = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnIncarcaDate = new javax.swing.JButton();
        btnIncarcaDate1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tpR = new javax.swing.JRadioButton();
        tmR = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOut = new javax.swing.JTextArea();
        btnIncarcaDate2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        textFisier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFisierActionPerformed(evt);
            }
        });

        jLabel1.setText("Nume fisier cu extensie .txt");

        btnIncarcaDate.setText("Incarca Date");
        btnIncarcaDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncarcaDateActionPerformed(evt);
            }
        });

        btnIncarcaDate1.setText("Trimite date la Server");
        btnIncarcaDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncarcaDate1ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tip", "Marca", "Serie", "Tonaj", "Capacitate", "CNP/Serii"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Tip clasa:");

        buttonGroup1.add(tpR);
        tpR.setText("Tren Pasageri");

        buttonGroup1.add(tmR);
        tmR.setText("Tren Marfa");

        jOut.setColumns(20);
        jOut.setRows(5);
        jScrollPane1.setViewportView(jOut);

        btnIncarcaDate2.setText("Coneteaza la server");
        btnIncarcaDate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncarcaDate2ActionPerformed(evt);
            }
        });

        jButton1.setText("Create XML");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Insert DB");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIncarcaDate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIncarcaDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFisier, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(tpR)
                    .addComponent(tmR)
                    .addComponent(btnIncarcaDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFisier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tpR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tmR)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncarcaDate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncarcaDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncarcaDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFisierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFisierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFisierActionPerformed

    private void btnIncarcaDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncarcaDateActionPerformed
        try {
            Component frame = null;
            String selected="";
            TrenPasageri pasageriReferinta=new TrenPasageri(0f,"Sample",12f,"Sample");
            TrenMarfa marfaReferinta=new TrenMarfa(0f,"Sample",12f,"Sample");
            String fisier= textFisier.getText();
            OperatiiOutFisier outPasageri=new OperatiiOutFisier(fisier);
            
            if(tmR.isSelected()){
                //citire de obiecte TrenMarfa
                selected="Este selectata clasa Tren Marfa";
                listaTren = outPasageri.citesteObiectDinFisierText(marfaReferinta);
            
                
            }else if(tpR.isSelected()){
                //citire de obiecte TrenPasageri
                selected="Este selectata clasa Tren Pasageri";
                listaTren = outPasageri.citesteObiectDinFisierText(pasageriReferinta);
            
            }  
            JOptionPane.showMessageDialog(frame,selected);
            
            for(Tren it:listaTren){
                
                if(tpR.isSelected()){
                    TrenPasageri test1=(TrenPasageri)it;
                    model.addRow(new Object[]{"Tren Pasageri",test1.getMarca() ,test1.getSerie(),Float.toString(test1.getTonaj()),Float.toString(test1.getCapacitate()),test1.getCnpCalatori()});
                }
                
                if(tmR.isSelected()){
                    TrenMarfa test1=(TrenMarfa)it;
                    model.addRow(new Object[]{"Tren Marfa",test1.getMarca() ,test1.getSerie(),Float.toString(test1.getTonaj()),Float.toString(test1.getCapacitate()),test1.getSerieMarfuri()});
                }
                
            }
        } catch (Exception ex) {
            Logger.getLogger(formular.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIncarcaDateActionPerformed

    private void btnIncarcaDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncarcaDate1ActionPerformed
        int lungimeLista=model.getRowCount();
        TrenPasageri pTMP;
        TrenMarfa mTMP;
        for(int i=0;i<lungimeLista;i++){
            String tip=(String)model.getValueAt(i,0);
            String marca=(String)model.getValueAt(i,1);
            String serie=(String)model.getValueAt(i,2);
            String tonaj=(String)model.getValueAt(i,3);
            String capacitate=(String)model.getValueAt(i,4);
//            String lis=(String)model.getValueAt(i,5);
            //String[] el=lis.split(",");
            Vector<String> v=(Vector<String>)model.getValueAt(i,5);
//            for(String j:el){
//                v.add(j);
//            }
            
            if(tip.equals("Tren Pasageri")){
                try {
                    pTMP=new TrenPasageri(Float.parseFloat(capacitate),serie,Float.parseFloat(tonaj),marca);
                    pTMP.setCnpCalatori(v);
                    listaTrimis.add(pTMP);
                    jOut.append("Se trimite la server " + pTMP + "\n");
                    fout.writeObject("TrenPasageri...\n");
                    fout.writeObject(pTMP);
                    
                } catch (Exception ex) {
                    Logger.getLogger(formular.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            if(tip.equals("Tren Marfa")){
                try {
                    mTMP=new TrenMarfa(Float.parseFloat(capacitate),serie,Float.parseFloat(tonaj),marca);
                    mTMP.setSerieMarfuri(v);
                    listaTrimis.add(mTMP);
                    jOut.append("Se trimite la server " + mTMP + "\n");
                    fout.writeObject("TrenMarfa...\n");
                    fout.writeObject(mTMP);
                    
                } catch (Exception ex) {
                    Logger.getLogger(formular.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } 
        
        
        
    }//GEN-LAST:event_btnIncarcaDate1ActionPerformed

    private void btnIncarcaDate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncarcaDate2ActionPerformed
        
        try {
            soc = new Socket("localhost",2001);
            out= soc.getOutputStream();
            in=soc.getInputStream();
            fin= new ObjectInputStream(in);
            fout = new ObjectOutputStream(out);
            jOut.append((String)fin.readObject()+"\n");
            
        } catch (IOException ex) {
            Logger.getLogger(formular.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formular.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnIncarcaDate2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            fout.writeObject(("Close server\n"));
            soc.close();
        } catch (IOException ex) {
            Logger.getLogger(formular.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            fout.writeObject("Insert");
        } catch (IOException ex) {
            Logger.getLogger(formular.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            fout.writeObject("XML");
        } catch (IOException ex) {
            Logger.getLogger(formular.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncarcaDate;
    private javax.swing.JButton btnIncarcaDate1;
    private javax.swing.JButton btnIncarcaDate2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jOut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textFisier;
    private javax.swing.JRadioButton tmR;
    private javax.swing.JRadioButton tpR;
    // End of variables declaration//GEN-END:variables
}
